# Generated by Django 2.1.1 on 2018-10-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Apelido do usuario')),
                ('nome', models.CharField(max_length=50, verbose_name='Primeiro nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=80, verbose_name='Senha Encriptada')),
                ('salt', models.CharField(max_length=16, verbose_name='Salt da senha')),
            ],
        ),
    ]
