# Generated by Django 2.1.1 on 2018-10-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('desc', models.TextField(verbose_name='Texto da Dica')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data e horario atual')),
                ('gasto', models.FloatField(verbose_name='Gasto em Reais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.Usuario')),
            ],
        ),
    ]
