# Generated by Django 2.1.1 on 2018-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dica',
            name='curtidas',
            field=models.IntegerField(default=0, verbose_name='Curtidas'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateField(verbose_name='Data e horario atual'),
        ),
    ]
